name: Echo CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build Docker image
        run: docker build -t jericho1994/echo-cicd:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push jericho1994/echo-cicd:latest

      - name: Simulate deployment (This is where deployment)
        run: |
          echo "Pulling Docker image"
          echo "Stopping container"
          echo "Starting container"

      - name: Checkout UI tests repo
        uses: actions/checkout@v4
        with:
          repository: jericho1994/Playwright-Test
          token: ${{ secrets.MYTOKEN }}
          path: ui-tests

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install UI test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright

      - name: Run UI tests
        run: |
          cd ui-tests\Playwright
          pytest -s tests\test_youtube_search.py::test_youtube_search_using_xpath

      - name: Notification (can be send to slack, smtp or other webhooks)
        if: success()
        run: echo "success"

      - name: Notification failed
        if: failure()
        run: echo "failed"