name: Echo CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------- Node.js --------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node dependencies
        run: npm install

      # -------- Python --------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Notification (can be send to slack, smtp or other webhooks)
        if: success()
        run: echo "success"

      - name: Notification failed
        if: failure()
        run: echo "failed"

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t jericho1994/echo-cicd:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push jericho1994/echo-cicd:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate deployment (This is where deployment)
        run: |
          echo "Pulling Docker image"
          echo "Stopping container"
          echo "Starting container"

  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI tests repo
        uses: actions/checkout@v4
        with:
          repository: jericho1994/Playwright-Test
          token: ${{ secrets.MYTOKEN }}
          path: ui-tests

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright

      - name: Install Playwright browsers
        run: |
          cd ui-tests/Playwright
          playwright install

      #- name: Run UI tests
      #  run: |
      #    cd ui-tests/Playwright
      #    HEADLESS=1 pytest -s tests/test_youtube_search.py::test_youtube_search_using_xpath